# Generated by Django 2.1.3 on 2019-01-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=15, verbose_name='账号')),
                ('pass_word', models.TextField(max_length=15, verbose_name='密码')),
                ('pjb_url', models.TextField(max_length=50, verbose_name='出借平台地址')),
                ('plan_id', models.IntegerField(verbose_name='出借产品')),
                ('invest_amount', models.BigIntegerField(verbose_name='出借金额')),
                ('invest_total', models.IntegerField(verbose_name='出借次数')),
                ('invest_status', models.BooleanField(default=False, verbose_name='出借状态')),
                ('product_type', models.IntegerField(verbose_name='产品类型')),
                ('err_msg', models.TextField(default='正常', max_length=255, verbose_name='错误日志')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
