# Generated by Django 2.1.3 on 2019-01-29 10:55

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0002_auto_20190129_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_match_type', models.TextField(max_length=10, verbose_name='产品类型')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.expressions.Case, to='invest_app.Product'),
        ),
        migrations.AddField(
            model_name='match',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.expressions.Case, to='invest_app.Invest'),
        ),
    ]
