# Generated by Django 2.1.3 on 2019-01-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0003_auto_20190129_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_match_type',
            field=models.TextField(max_length=20, verbose_name='产品类型'),
        ),
    ]
